/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppVendasRouteImport } from './routes/_app/vendas'
import { Route as AppTarefasRouteImport } from './routes/_app/tarefas'
import { Route as AppSuperAdminRouteImport } from './routes/_app/super-admin'
import { Route as AppRelatoriosRouteImport } from './routes/_app/relatorios'
import { Route as AppPosVendaRouteImport } from './routes/_app/pos-venda'
import { Route as AppPerfilRouteImport } from './routes/_app/perfil'
import { Route as AppPdvRouteImport } from './routes/_app/pdv'
import { Route as AppNotificacoesRouteImport } from './routes/_app/notificacoes'
import { Route as AppImportacaoRouteImport } from './routes/_app/importacao'
import { Route as AppFiscalRouteImport } from './routes/_app/fiscal'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppControleRouteImport } from './routes/_app/controle'
import { Route as AppConfiguracoesRouteImport } from './routes/_app/configuracoes'
import { Route as AppComprasRouteImport } from './routes/_app/compras'
import { Route as AppChatRouteImport } from './routes/_app/chat'
import { Route as AppCadastrosRouteImport } from './routes/_app/cadastros'
import { Route as AppBpoRouteImport } from './routes/_app/bpo'
import { Route as AppAgendaRouteImport } from './routes/_app/agenda'
import { Route as AppSuperAdminIndexRouteImport } from './routes/_app/super-admin/index'
import { Route as AppPdvIndexRouteImport } from './routes/_app/pdv/index'
import { Route as AppFinanceiroIndexRouteImport } from './routes/_app/financeiro/index'
import { Route as AppEstoqueIndexRouteImport } from './routes/_app/estoque/index'
import { Route as AppBpoIndexRouteImport } from './routes/_app/bpo/index'
import { Route as AppSuperAdminUsoRouteImport } from './routes/_app/super-admin/uso'
import { Route as AppSuperAdminPlanosRouteImport } from './routes/_app/super-admin/planos'
import { Route as AppSuperAdminNovaEmpresaRouteImport } from './routes/_app/super-admin/nova-empresa'
import { Route as AppSuperAdminEmpresasRouteImport } from './routes/_app/super-admin/empresas'
import { Route as AppSuperAdminAssinaturasRouteImport } from './routes/_app/super-admin/assinaturas'
import { Route as AppPdvVisaoGeralRouteImport } from './routes/_app/pdv/visao-geral'
import { Route as AppPdvTrocasDevolucoesRouteImport } from './routes/_app/pdv/trocas-devolucoes'
import { Route as AppPdvHistoricoRouteImport } from './routes/_app/pdv/historico'
import { Route as AppPdvFiscalRouteImport } from './routes/_app/pdv/fiscal'
import { Route as AppPdvConfiguracoesRouteImport } from './routes/_app/pdv/configuracoes'
import { Route as AppPdvCaixaRouteImport } from './routes/_app/pdv/caixa'
import { Route as AppFinanceiroTarefasRouteImport } from './routes/_app/financeiro/tarefas'
import { Route as AppFinanceiroNotificacoesRouteImport } from './routes/_app/financeiro/notificacoes'
import { Route as AppFinanceiroFluxoCaixaRouteImport } from './routes/_app/financeiro/fluxo-caixa'
import { Route as AppFinanceiroDreRouteImport } from './routes/_app/financeiro/dre'
import { Route as AppFinanceiroContasCarteirasRouteImport } from './routes/_app/financeiro/contas-carteiras'
import { Route as AppFinanceiroContasAReceberRouteImport } from './routes/_app/financeiro/contas-a-receber'
import { Route as AppFinanceiroContasAPagarRouteImport } from './routes/_app/financeiro/contas-a-pagar'
import { Route as AppFinanceiroConciliacaoRouteImport } from './routes/_app/financeiro/conciliacao'
import { Route as AppFinanceiroCobrancasRouteImport } from './routes/_app/financeiro/cobrancas'
import { Route as AppFinanceiroCartoesRouteImport } from './routes/_app/financeiro/cartoes'
import { Route as AppEstoqueTransferenciasRouteImport } from './routes/_app/estoque/transferencias'
import { Route as AppEstoqueReposicaoRouteImport } from './routes/_app/estoque/reposicao'
import { Route as AppEstoqueRecebimentoRouteImport } from './routes/_app/estoque/recebimento'
import { Route as AppEstoqueProdutosRouteImport } from './routes/_app/estoque/produtos'
import { Route as AppEstoquePerdasRouteImport } from './routes/_app/estoque/perdas'
import { Route as AppEstoqueMovimentacoesRouteImport } from './routes/_app/estoque/movimentacoes'
import { Route as AppEstoqueLocaisRouteImport } from './routes/_app/estoque/locais'
import { Route as AppEstoqueInventarioRouteImport } from './routes/_app/estoque/inventario'
import { Route as AppEstoqueConsultaRouteImport } from './routes/_app/estoque/consulta'
import { Route as AppBpoTarefasRouteImport } from './routes/_app/bpo/tarefas'
import { Route as AppBpoRelatoriosRouteImport } from './routes/_app/bpo/relatorios'
import { Route as AppBpoPendenciasRouteImport } from './routes/_app/bpo/pendencias'
import { Route as AppBpoLancamentosRouteImport } from './routes/_app/bpo/lancamentos'
import { Route as AppBpoHonorariosRouteImport } from './routes/_app/bpo/honorarios'
import { Route as AppBpoFechamentoRouteImport } from './routes/_app/bpo/fechamento'
import { Route as AppBpoDocumentosRouteImport } from './routes/_app/bpo/documentos'
import { Route as AppBpoConfiguracoesRouteImport } from './routes/_app/bpo/configuracoes'
import { Route as AppBpoConciliacaoRouteImport } from './routes/_app/bpo/conciliacao'
import { Route as AppBpoComunicacaoRouteImport } from './routes/_app/bpo/comunicacao'
import { Route as AppBpoClientesRouteImport } from './routes/_app/bpo/clientes'
import { Route as AppBpoAnaliseRouteImport } from './routes/_app/bpo/analise'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVendasRoute = AppVendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => AppRoute,
} as any)
const AppTarefasRoute = AppTarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => AppRoute,
} as any)
const AppSuperAdminRoute = AppSuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppPosVendaRoute = AppPosVendaRouteImport.update({
  id: '/pos-venda',
  path: '/pos-venda',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppPdvRoute = AppPdvRouteImport.update({
  id: '/pdv',
  path: '/pdv',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificacoesRoute = AppNotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppImportacaoRoute = AppImportacaoRouteImport.update({
  id: '/importacao',
  path: '/importacao',
  getParentRoute: () => AppRoute,
} as any)
const AppFiscalRoute = AppFiscalRouteImport.update({
  id: '/fiscal',
  path: '/fiscal',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppControleRoute = AppControleRouteImport.update({
  id: '/controle',
  path: '/controle',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppComprasRoute = AppComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppCadastrosRoute = AppCadastrosRouteImport.update({
  id: '/cadastros',
  path: '/cadastros',
  getParentRoute: () => AppRoute,
} as any)
const AppBpoRoute = AppBpoRouteImport.update({
  id: '/bpo',
  path: '/bpo',
  getParentRoute: () => AppRoute,
} as any)
const AppAgendaRoute = AppAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AppRoute,
} as any)
const AppSuperAdminIndexRoute = AppSuperAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSuperAdminRoute,
} as any)
const AppPdvIndexRoute = AppPdvIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPdvRoute,
} as any)
const AppFinanceiroIndexRoute = AppFinanceiroIndexRouteImport.update({
  id: '/financeiro/',
  path: '/financeiro/',
  getParentRoute: () => AppRoute,
} as any)
const AppEstoqueIndexRoute = AppEstoqueIndexRouteImport.update({
  id: '/estoque/',
  path: '/estoque/',
  getParentRoute: () => AppRoute,
} as any)
const AppBpoIndexRoute = AppBpoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppBpoRoute,
} as any)
const AppSuperAdminUsoRoute = AppSuperAdminUsoRouteImport.update({
  id: '/uso',
  path: '/uso',
  getParentRoute: () => AppSuperAdminRoute,
} as any)
const AppSuperAdminPlanosRoute = AppSuperAdminPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => AppSuperAdminRoute,
} as any)
const AppSuperAdminNovaEmpresaRoute =
  AppSuperAdminNovaEmpresaRouteImport.update({
    id: '/nova-empresa',
    path: '/nova-empresa',
    getParentRoute: () => AppSuperAdminRoute,
  } as any)
const AppSuperAdminEmpresasRoute = AppSuperAdminEmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => AppSuperAdminRoute,
} as any)
const AppSuperAdminAssinaturasRoute =
  AppSuperAdminAssinaturasRouteImport.update({
    id: '/assinaturas',
    path: '/assinaturas',
    getParentRoute: () => AppSuperAdminRoute,
  } as any)
const AppPdvVisaoGeralRoute = AppPdvVisaoGeralRouteImport.update({
  id: '/visao-geral',
  path: '/visao-geral',
  getParentRoute: () => AppPdvRoute,
} as any)
const AppPdvTrocasDevolucoesRoute = AppPdvTrocasDevolucoesRouteImport.update({
  id: '/trocas-devolucoes',
  path: '/trocas-devolucoes',
  getParentRoute: () => AppPdvRoute,
} as any)
const AppPdvHistoricoRoute = AppPdvHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AppPdvRoute,
} as any)
const AppPdvFiscalRoute = AppPdvFiscalRouteImport.update({
  id: '/fiscal',
  path: '/fiscal',
  getParentRoute: () => AppPdvRoute,
} as any)
const AppPdvConfiguracoesRoute = AppPdvConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppPdvRoute,
} as any)
const AppPdvCaixaRoute = AppPdvCaixaRouteImport.update({
  id: '/caixa',
  path: '/caixa',
  getParentRoute: () => AppPdvRoute,
} as any)
const AppFinanceiroTarefasRoute = AppFinanceiroTarefasRouteImport.update({
  id: '/financeiro/tarefas',
  path: '/financeiro/tarefas',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroNotificacoesRoute =
  AppFinanceiroNotificacoesRouteImport.update({
    id: '/financeiro/notificacoes',
    path: '/financeiro/notificacoes',
    getParentRoute: () => AppRoute,
  } as any)
const AppFinanceiroFluxoCaixaRoute = AppFinanceiroFluxoCaixaRouteImport.update({
  id: '/financeiro/fluxo-caixa',
  path: '/financeiro/fluxo-caixa',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroDreRoute = AppFinanceiroDreRouteImport.update({
  id: '/financeiro/dre',
  path: '/financeiro/dre',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroContasCarteirasRoute =
  AppFinanceiroContasCarteirasRouteImport.update({
    id: '/financeiro/contas-carteiras',
    path: '/financeiro/contas-carteiras',
    getParentRoute: () => AppRoute,
  } as any)
const AppFinanceiroContasAReceberRoute =
  AppFinanceiroContasAReceberRouteImport.update({
    id: '/financeiro/contas-a-receber',
    path: '/financeiro/contas-a-receber',
    getParentRoute: () => AppRoute,
  } as any)
const AppFinanceiroContasAPagarRoute =
  AppFinanceiroContasAPagarRouteImport.update({
    id: '/financeiro/contas-a-pagar',
    path: '/financeiro/contas-a-pagar',
    getParentRoute: () => AppRoute,
  } as any)
const AppFinanceiroConciliacaoRoute =
  AppFinanceiroConciliacaoRouteImport.update({
    id: '/financeiro/conciliacao',
    path: '/financeiro/conciliacao',
    getParentRoute: () => AppRoute,
  } as any)
const AppFinanceiroCobrancasRoute = AppFinanceiroCobrancasRouteImport.update({
  id: '/financeiro/cobrancas',
  path: '/financeiro/cobrancas',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroCartoesRoute = AppFinanceiroCartoesRouteImport.update({
  id: '/financeiro/cartoes',
  path: '/financeiro/cartoes',
  getParentRoute: () => AppRoute,
} as any)
const AppEstoqueTransferenciasRoute =
  AppEstoqueTransferenciasRouteImport.update({
    id: '/estoque/transferencias',
    path: '/estoque/transferencias',
    getParentRoute: () => AppRoute,
  } as any)
const AppEstoqueReposicaoRoute = AppEstoqueReposicaoRouteImport.update({
  id: '/estoque/reposicao',
  path: '/estoque/reposicao',
  getParentRoute: () => AppRoute,
} as any)
const AppEstoqueRecebimentoRoute = AppEstoqueRecebimentoRouteImport.update({
  id: '/estoque/recebimento',
  path: '/estoque/recebimento',
  getParentRoute: () => AppRoute,
} as any)
const AppEstoqueProdutosRoute = AppEstoqueProdutosRouteImport.update({
  id: '/estoque/produtos',
  path: '/estoque/produtos',
  getParentRoute: () => AppRoute,
} as any)
const AppEstoquePerdasRoute = AppEstoquePerdasRouteImport.update({
  id: '/estoque/perdas',
  path: '/estoque/perdas',
  getParentRoute: () => AppRoute,
} as any)
const AppEstoqueMovimentacoesRoute = AppEstoqueMovimentacoesRouteImport.update({
  id: '/estoque/movimentacoes',
  path: '/estoque/movimentacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppEstoqueLocaisRoute = AppEstoqueLocaisRouteImport.update({
  id: '/estoque/locais',
  path: '/estoque/locais',
  getParentRoute: () => AppRoute,
} as any)
const AppEstoqueInventarioRoute = AppEstoqueInventarioRouteImport.update({
  id: '/estoque/inventario',
  path: '/estoque/inventario',
  getParentRoute: () => AppRoute,
} as any)
const AppEstoqueConsultaRoute = AppEstoqueConsultaRouteImport.update({
  id: '/estoque/consulta',
  path: '/estoque/consulta',
  getParentRoute: () => AppRoute,
} as any)
const AppBpoTarefasRoute = AppBpoTarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => AppBpoRoute,
} as any)
const AppBpoRelatoriosRoute = AppBpoRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppBpoRoute,
} as any)
const AppBpoPendenciasRoute = AppBpoPendenciasRouteImport.update({
  id: '/pendencias',
  path: '/pendencias',
  getParentRoute: () => AppBpoRoute,
} as any)
const AppBpoLancamentosRoute = AppBpoLancamentosRouteImport.update({
  id: '/lancamentos',
  path: '/lancamentos',
  getParentRoute: () => AppBpoRoute,
} as any)
const AppBpoHonorariosRoute = AppBpoHonorariosRouteImport.update({
  id: '/honorarios',
  path: '/honorarios',
  getParentRoute: () => AppBpoRoute,
} as any)
const AppBpoFechamentoRoute = AppBpoFechamentoRouteImport.update({
  id: '/fechamento',
  path: '/fechamento',
  getParentRoute: () => AppBpoRoute,
} as any)
const AppBpoDocumentosRoute = AppBpoDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => AppBpoRoute,
} as any)
const AppBpoConfiguracoesRoute = AppBpoConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppBpoRoute,
} as any)
const AppBpoConciliacaoRoute = AppBpoConciliacaoRouteImport.update({
  id: '/conciliacao',
  path: '/conciliacao',
  getParentRoute: () => AppBpoRoute,
} as any)
const AppBpoComunicacaoRoute = AppBpoComunicacaoRouteImport.update({
  id: '/comunicacao',
  path: '/comunicacao',
  getParentRoute: () => AppBpoRoute,
} as any)
const AppBpoClientesRoute = AppBpoClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppBpoRoute,
} as any)
const AppBpoAnaliseRoute = AppBpoAnaliseRouteImport.update({
  id: '/analise',
  path: '/analise',
  getParentRoute: () => AppBpoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/agenda': typeof AppAgendaRoute
  '/bpo': typeof AppBpoRouteWithChildren
  '/cadastros': typeof AppCadastrosRoute
  '/chat': typeof AppChatRoute
  '/compras': typeof AppComprasRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/controle': typeof AppControleRoute
  '/dashboard': typeof AppDashboardRoute
  '/fiscal': typeof AppFiscalRoute
  '/importacao': typeof AppImportacaoRoute
  '/notificacoes': typeof AppNotificacoesRoute
  '/pdv': typeof AppPdvRouteWithChildren
  '/perfil': typeof AppPerfilRoute
  '/pos-venda': typeof AppPosVendaRoute
  '/relatorios': typeof AppRelatoriosRoute
  '/super-admin': typeof AppSuperAdminRouteWithChildren
  '/tarefas': typeof AppTarefasRoute
  '/vendas': typeof AppVendasRoute
  '/bpo/analise': typeof AppBpoAnaliseRoute
  '/bpo/clientes': typeof AppBpoClientesRoute
  '/bpo/comunicacao': typeof AppBpoComunicacaoRoute
  '/bpo/conciliacao': typeof AppBpoConciliacaoRoute
  '/bpo/configuracoes': typeof AppBpoConfiguracoesRoute
  '/bpo/documentos': typeof AppBpoDocumentosRoute
  '/bpo/fechamento': typeof AppBpoFechamentoRoute
  '/bpo/honorarios': typeof AppBpoHonorariosRoute
  '/bpo/lancamentos': typeof AppBpoLancamentosRoute
  '/bpo/pendencias': typeof AppBpoPendenciasRoute
  '/bpo/relatorios': typeof AppBpoRelatoriosRoute
  '/bpo/tarefas': typeof AppBpoTarefasRoute
  '/estoque/consulta': typeof AppEstoqueConsultaRoute
  '/estoque/inventario': typeof AppEstoqueInventarioRoute
  '/estoque/locais': typeof AppEstoqueLocaisRoute
  '/estoque/movimentacoes': typeof AppEstoqueMovimentacoesRoute
  '/estoque/perdas': typeof AppEstoquePerdasRoute
  '/estoque/produtos': typeof AppEstoqueProdutosRoute
  '/estoque/recebimento': typeof AppEstoqueRecebimentoRoute
  '/estoque/reposicao': typeof AppEstoqueReposicaoRoute
  '/estoque/transferencias': typeof AppEstoqueTransferenciasRoute
  '/financeiro/cartoes': typeof AppFinanceiroCartoesRoute
  '/financeiro/cobrancas': typeof AppFinanceiroCobrancasRoute
  '/financeiro/conciliacao': typeof AppFinanceiroConciliacaoRoute
  '/financeiro/contas-a-pagar': typeof AppFinanceiroContasAPagarRoute
  '/financeiro/contas-a-receber': typeof AppFinanceiroContasAReceberRoute
  '/financeiro/contas-carteiras': typeof AppFinanceiroContasCarteirasRoute
  '/financeiro/dre': typeof AppFinanceiroDreRoute
  '/financeiro/fluxo-caixa': typeof AppFinanceiroFluxoCaixaRoute
  '/financeiro/notificacoes': typeof AppFinanceiroNotificacoesRoute
  '/financeiro/tarefas': typeof AppFinanceiroTarefasRoute
  '/pdv/caixa': typeof AppPdvCaixaRoute
  '/pdv/configuracoes': typeof AppPdvConfiguracoesRoute
  '/pdv/fiscal': typeof AppPdvFiscalRoute
  '/pdv/historico': typeof AppPdvHistoricoRoute
  '/pdv/trocas-devolucoes': typeof AppPdvTrocasDevolucoesRoute
  '/pdv/visao-geral': typeof AppPdvVisaoGeralRoute
  '/super-admin/assinaturas': typeof AppSuperAdminAssinaturasRoute
  '/super-admin/empresas': typeof AppSuperAdminEmpresasRoute
  '/super-admin/nova-empresa': typeof AppSuperAdminNovaEmpresaRoute
  '/super-admin/planos': typeof AppSuperAdminPlanosRoute
  '/super-admin/uso': typeof AppSuperAdminUsoRoute
  '/bpo/': typeof AppBpoIndexRoute
  '/estoque/': typeof AppEstoqueIndexRoute
  '/financeiro/': typeof AppFinanceiroIndexRoute
  '/pdv/': typeof AppPdvIndexRoute
  '/super-admin/': typeof AppSuperAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/agenda': typeof AppAgendaRoute
  '/cadastros': typeof AppCadastrosRoute
  '/chat': typeof AppChatRoute
  '/compras': typeof AppComprasRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/controle': typeof AppControleRoute
  '/dashboard': typeof AppDashboardRoute
  '/fiscal': typeof AppFiscalRoute
  '/importacao': typeof AppImportacaoRoute
  '/notificacoes': typeof AppNotificacoesRoute
  '/perfil': typeof AppPerfilRoute
  '/pos-venda': typeof AppPosVendaRoute
  '/relatorios': typeof AppRelatoriosRoute
  '/tarefas': typeof AppTarefasRoute
  '/vendas': typeof AppVendasRoute
  '/bpo/analise': typeof AppBpoAnaliseRoute
  '/bpo/clientes': typeof AppBpoClientesRoute
  '/bpo/comunicacao': typeof AppBpoComunicacaoRoute
  '/bpo/conciliacao': typeof AppBpoConciliacaoRoute
  '/bpo/configuracoes': typeof AppBpoConfiguracoesRoute
  '/bpo/documentos': typeof AppBpoDocumentosRoute
  '/bpo/fechamento': typeof AppBpoFechamentoRoute
  '/bpo/honorarios': typeof AppBpoHonorariosRoute
  '/bpo/lancamentos': typeof AppBpoLancamentosRoute
  '/bpo/pendencias': typeof AppBpoPendenciasRoute
  '/bpo/relatorios': typeof AppBpoRelatoriosRoute
  '/bpo/tarefas': typeof AppBpoTarefasRoute
  '/estoque/consulta': typeof AppEstoqueConsultaRoute
  '/estoque/inventario': typeof AppEstoqueInventarioRoute
  '/estoque/locais': typeof AppEstoqueLocaisRoute
  '/estoque/movimentacoes': typeof AppEstoqueMovimentacoesRoute
  '/estoque/perdas': typeof AppEstoquePerdasRoute
  '/estoque/produtos': typeof AppEstoqueProdutosRoute
  '/estoque/recebimento': typeof AppEstoqueRecebimentoRoute
  '/estoque/reposicao': typeof AppEstoqueReposicaoRoute
  '/estoque/transferencias': typeof AppEstoqueTransferenciasRoute
  '/financeiro/cartoes': typeof AppFinanceiroCartoesRoute
  '/financeiro/cobrancas': typeof AppFinanceiroCobrancasRoute
  '/financeiro/conciliacao': typeof AppFinanceiroConciliacaoRoute
  '/financeiro/contas-a-pagar': typeof AppFinanceiroContasAPagarRoute
  '/financeiro/contas-a-receber': typeof AppFinanceiroContasAReceberRoute
  '/financeiro/contas-carteiras': typeof AppFinanceiroContasCarteirasRoute
  '/financeiro/dre': typeof AppFinanceiroDreRoute
  '/financeiro/fluxo-caixa': typeof AppFinanceiroFluxoCaixaRoute
  '/financeiro/notificacoes': typeof AppFinanceiroNotificacoesRoute
  '/financeiro/tarefas': typeof AppFinanceiroTarefasRoute
  '/pdv/caixa': typeof AppPdvCaixaRoute
  '/pdv/configuracoes': typeof AppPdvConfiguracoesRoute
  '/pdv/fiscal': typeof AppPdvFiscalRoute
  '/pdv/historico': typeof AppPdvHistoricoRoute
  '/pdv/trocas-devolucoes': typeof AppPdvTrocasDevolucoesRoute
  '/pdv/visao-geral': typeof AppPdvVisaoGeralRoute
  '/super-admin/assinaturas': typeof AppSuperAdminAssinaturasRoute
  '/super-admin/empresas': typeof AppSuperAdminEmpresasRoute
  '/super-admin/nova-empresa': typeof AppSuperAdminNovaEmpresaRoute
  '/super-admin/planos': typeof AppSuperAdminPlanosRoute
  '/super-admin/uso': typeof AppSuperAdminUsoRoute
  '/bpo': typeof AppBpoIndexRoute
  '/estoque': typeof AppEstoqueIndexRoute
  '/financeiro': typeof AppFinanceiroIndexRoute
  '/pdv': typeof AppPdvIndexRoute
  '/super-admin': typeof AppSuperAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/agenda': typeof AppAgendaRoute
  '/_app/bpo': typeof AppBpoRouteWithChildren
  '/_app/cadastros': typeof AppCadastrosRoute
  '/_app/chat': typeof AppChatRoute
  '/_app/compras': typeof AppComprasRoute
  '/_app/configuracoes': typeof AppConfiguracoesRoute
  '/_app/controle': typeof AppControleRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/fiscal': typeof AppFiscalRoute
  '/_app/importacao': typeof AppImportacaoRoute
  '/_app/notificacoes': typeof AppNotificacoesRoute
  '/_app/pdv': typeof AppPdvRouteWithChildren
  '/_app/perfil': typeof AppPerfilRoute
  '/_app/pos-venda': typeof AppPosVendaRoute
  '/_app/relatorios': typeof AppRelatoriosRoute
  '/_app/super-admin': typeof AppSuperAdminRouteWithChildren
  '/_app/tarefas': typeof AppTarefasRoute
  '/_app/vendas': typeof AppVendasRoute
  '/_app/bpo/analise': typeof AppBpoAnaliseRoute
  '/_app/bpo/clientes': typeof AppBpoClientesRoute
  '/_app/bpo/comunicacao': typeof AppBpoComunicacaoRoute
  '/_app/bpo/conciliacao': typeof AppBpoConciliacaoRoute
  '/_app/bpo/configuracoes': typeof AppBpoConfiguracoesRoute
  '/_app/bpo/documentos': typeof AppBpoDocumentosRoute
  '/_app/bpo/fechamento': typeof AppBpoFechamentoRoute
  '/_app/bpo/honorarios': typeof AppBpoHonorariosRoute
  '/_app/bpo/lancamentos': typeof AppBpoLancamentosRoute
  '/_app/bpo/pendencias': typeof AppBpoPendenciasRoute
  '/_app/bpo/relatorios': typeof AppBpoRelatoriosRoute
  '/_app/bpo/tarefas': typeof AppBpoTarefasRoute
  '/_app/estoque/consulta': typeof AppEstoqueConsultaRoute
  '/_app/estoque/inventario': typeof AppEstoqueInventarioRoute
  '/_app/estoque/locais': typeof AppEstoqueLocaisRoute
  '/_app/estoque/movimentacoes': typeof AppEstoqueMovimentacoesRoute
  '/_app/estoque/perdas': typeof AppEstoquePerdasRoute
  '/_app/estoque/produtos': typeof AppEstoqueProdutosRoute
  '/_app/estoque/recebimento': typeof AppEstoqueRecebimentoRoute
  '/_app/estoque/reposicao': typeof AppEstoqueReposicaoRoute
  '/_app/estoque/transferencias': typeof AppEstoqueTransferenciasRoute
  '/_app/financeiro/cartoes': typeof AppFinanceiroCartoesRoute
  '/_app/financeiro/cobrancas': typeof AppFinanceiroCobrancasRoute
  '/_app/financeiro/conciliacao': typeof AppFinanceiroConciliacaoRoute
  '/_app/financeiro/contas-a-pagar': typeof AppFinanceiroContasAPagarRoute
  '/_app/financeiro/contas-a-receber': typeof AppFinanceiroContasAReceberRoute
  '/_app/financeiro/contas-carteiras': typeof AppFinanceiroContasCarteirasRoute
  '/_app/financeiro/dre': typeof AppFinanceiroDreRoute
  '/_app/financeiro/fluxo-caixa': typeof AppFinanceiroFluxoCaixaRoute
  '/_app/financeiro/notificacoes': typeof AppFinanceiroNotificacoesRoute
  '/_app/financeiro/tarefas': typeof AppFinanceiroTarefasRoute
  '/_app/pdv/caixa': typeof AppPdvCaixaRoute
  '/_app/pdv/configuracoes': typeof AppPdvConfiguracoesRoute
  '/_app/pdv/fiscal': typeof AppPdvFiscalRoute
  '/_app/pdv/historico': typeof AppPdvHistoricoRoute
  '/_app/pdv/trocas-devolucoes': typeof AppPdvTrocasDevolucoesRoute
  '/_app/pdv/visao-geral': typeof AppPdvVisaoGeralRoute
  '/_app/super-admin/assinaturas': typeof AppSuperAdminAssinaturasRoute
  '/_app/super-admin/empresas': typeof AppSuperAdminEmpresasRoute
  '/_app/super-admin/nova-empresa': typeof AppSuperAdminNovaEmpresaRoute
  '/_app/super-admin/planos': typeof AppSuperAdminPlanosRoute
  '/_app/super-admin/uso': typeof AppSuperAdminUsoRoute
  '/_app/bpo/': typeof AppBpoIndexRoute
  '/_app/estoque/': typeof AppEstoqueIndexRoute
  '/_app/financeiro/': typeof AppFinanceiroIndexRoute
  '/_app/pdv/': typeof AppPdvIndexRoute
  '/_app/super-admin/': typeof AppSuperAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/agenda'
    | '/bpo'
    | '/cadastros'
    | '/chat'
    | '/compras'
    | '/configuracoes'
    | '/controle'
    | '/dashboard'
    | '/fiscal'
    | '/importacao'
    | '/notificacoes'
    | '/pdv'
    | '/perfil'
    | '/pos-venda'
    | '/relatorios'
    | '/super-admin'
    | '/tarefas'
    | '/vendas'
    | '/bpo/analise'
    | '/bpo/clientes'
    | '/bpo/comunicacao'
    | '/bpo/conciliacao'
    | '/bpo/configuracoes'
    | '/bpo/documentos'
    | '/bpo/fechamento'
    | '/bpo/honorarios'
    | '/bpo/lancamentos'
    | '/bpo/pendencias'
    | '/bpo/relatorios'
    | '/bpo/tarefas'
    | '/estoque/consulta'
    | '/estoque/inventario'
    | '/estoque/locais'
    | '/estoque/movimentacoes'
    | '/estoque/perdas'
    | '/estoque/produtos'
    | '/estoque/recebimento'
    | '/estoque/reposicao'
    | '/estoque/transferencias'
    | '/financeiro/cartoes'
    | '/financeiro/cobrancas'
    | '/financeiro/conciliacao'
    | '/financeiro/contas-a-pagar'
    | '/financeiro/contas-a-receber'
    | '/financeiro/contas-carteiras'
    | '/financeiro/dre'
    | '/financeiro/fluxo-caixa'
    | '/financeiro/notificacoes'
    | '/financeiro/tarefas'
    | '/pdv/caixa'
    | '/pdv/configuracoes'
    | '/pdv/fiscal'
    | '/pdv/historico'
    | '/pdv/trocas-devolucoes'
    | '/pdv/visao-geral'
    | '/super-admin/assinaturas'
    | '/super-admin/empresas'
    | '/super-admin/nova-empresa'
    | '/super-admin/planos'
    | '/super-admin/uso'
    | '/bpo/'
    | '/estoque/'
    | '/financeiro/'
    | '/pdv/'
    | '/super-admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/agenda'
    | '/cadastros'
    | '/chat'
    | '/compras'
    | '/configuracoes'
    | '/controle'
    | '/dashboard'
    | '/fiscal'
    | '/importacao'
    | '/notificacoes'
    | '/perfil'
    | '/pos-venda'
    | '/relatorios'
    | '/tarefas'
    | '/vendas'
    | '/bpo/analise'
    | '/bpo/clientes'
    | '/bpo/comunicacao'
    | '/bpo/conciliacao'
    | '/bpo/configuracoes'
    | '/bpo/documentos'
    | '/bpo/fechamento'
    | '/bpo/honorarios'
    | '/bpo/lancamentos'
    | '/bpo/pendencias'
    | '/bpo/relatorios'
    | '/bpo/tarefas'
    | '/estoque/consulta'
    | '/estoque/inventario'
    | '/estoque/locais'
    | '/estoque/movimentacoes'
    | '/estoque/perdas'
    | '/estoque/produtos'
    | '/estoque/recebimento'
    | '/estoque/reposicao'
    | '/estoque/transferencias'
    | '/financeiro/cartoes'
    | '/financeiro/cobrancas'
    | '/financeiro/conciliacao'
    | '/financeiro/contas-a-pagar'
    | '/financeiro/contas-a-receber'
    | '/financeiro/contas-carteiras'
    | '/financeiro/dre'
    | '/financeiro/fluxo-caixa'
    | '/financeiro/notificacoes'
    | '/financeiro/tarefas'
    | '/pdv/caixa'
    | '/pdv/configuracoes'
    | '/pdv/fiscal'
    | '/pdv/historico'
    | '/pdv/trocas-devolucoes'
    | '/pdv/visao-geral'
    | '/super-admin/assinaturas'
    | '/super-admin/empresas'
    | '/super-admin/nova-empresa'
    | '/super-admin/planos'
    | '/super-admin/uso'
    | '/bpo'
    | '/estoque'
    | '/financeiro'
    | '/pdv'
    | '/super-admin'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/agenda'
    | '/_app/bpo'
    | '/_app/cadastros'
    | '/_app/chat'
    | '/_app/compras'
    | '/_app/configuracoes'
    | '/_app/controle'
    | '/_app/dashboard'
    | '/_app/fiscal'
    | '/_app/importacao'
    | '/_app/notificacoes'
    | '/_app/pdv'
    | '/_app/perfil'
    | '/_app/pos-venda'
    | '/_app/relatorios'
    | '/_app/super-admin'
    | '/_app/tarefas'
    | '/_app/vendas'
    | '/_app/bpo/analise'
    | '/_app/bpo/clientes'
    | '/_app/bpo/comunicacao'
    | '/_app/bpo/conciliacao'
    | '/_app/bpo/configuracoes'
    | '/_app/bpo/documentos'
    | '/_app/bpo/fechamento'
    | '/_app/bpo/honorarios'
    | '/_app/bpo/lancamentos'
    | '/_app/bpo/pendencias'
    | '/_app/bpo/relatorios'
    | '/_app/bpo/tarefas'
    | '/_app/estoque/consulta'
    | '/_app/estoque/inventario'
    | '/_app/estoque/locais'
    | '/_app/estoque/movimentacoes'
    | '/_app/estoque/perdas'
    | '/_app/estoque/produtos'
    | '/_app/estoque/recebimento'
    | '/_app/estoque/reposicao'
    | '/_app/estoque/transferencias'
    | '/_app/financeiro/cartoes'
    | '/_app/financeiro/cobrancas'
    | '/_app/financeiro/conciliacao'
    | '/_app/financeiro/contas-a-pagar'
    | '/_app/financeiro/contas-a-receber'
    | '/_app/financeiro/contas-carteiras'
    | '/_app/financeiro/dre'
    | '/_app/financeiro/fluxo-caixa'
    | '/_app/financeiro/notificacoes'
    | '/_app/financeiro/tarefas'
    | '/_app/pdv/caixa'
    | '/_app/pdv/configuracoes'
    | '/_app/pdv/fiscal'
    | '/_app/pdv/historico'
    | '/_app/pdv/trocas-devolucoes'
    | '/_app/pdv/visao-geral'
    | '/_app/super-admin/assinaturas'
    | '/_app/super-admin/empresas'
    | '/_app/super-admin/nova-empresa'
    | '/_app/super-admin/planos'
    | '/_app/super-admin/uso'
    | '/_app/bpo/'
    | '/_app/estoque/'
    | '/_app/financeiro/'
    | '/_app/pdv/'
    | '/_app/super-admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/vendas': {
      id: '/_app/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof AppVendasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tarefas': {
      id: '/_app/tarefas'
      path: '/tarefas'
      fullPath: '/tarefas'
      preLoaderRoute: typeof AppTarefasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/super-admin': {
      id: '/_app/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof AppSuperAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/relatorios': {
      id: '/_app/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pos-venda': {
      id: '/_app/pos-venda'
      path: '/pos-venda'
      fullPath: '/pos-venda'
      preLoaderRoute: typeof AppPosVendaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/perfil': {
      id: '/_app/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pdv': {
      id: '/_app/pdv'
      path: '/pdv'
      fullPath: '/pdv'
      preLoaderRoute: typeof AppPdvRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notificacoes': {
      id: '/_app/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof AppNotificacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/importacao': {
      id: '/_app/importacao'
      path: '/importacao'
      fullPath: '/importacao'
      preLoaderRoute: typeof AppImportacaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fiscal': {
      id: '/_app/fiscal'
      path: '/fiscal'
      fullPath: '/fiscal'
      preLoaderRoute: typeof AppFiscalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/controle': {
      id: '/_app/controle'
      path: '/controle'
      fullPath: '/controle'
      preLoaderRoute: typeof AppControleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracoes': {
      id: '/_app/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/compras': {
      id: '/_app/compras'
      path: '/compras'
      fullPath: '/compras'
      preLoaderRoute: typeof AppComprasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cadastros': {
      id: '/_app/cadastros'
      path: '/cadastros'
      fullPath: '/cadastros'
      preLoaderRoute: typeof AppCadastrosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bpo': {
      id: '/_app/bpo'
      path: '/bpo'
      fullPath: '/bpo'
      preLoaderRoute: typeof AppBpoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agenda': {
      id: '/_app/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AppAgendaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/super-admin/': {
      id: '/_app/super-admin/'
      path: '/'
      fullPath: '/super-admin/'
      preLoaderRoute: typeof AppSuperAdminIndexRouteImport
      parentRoute: typeof AppSuperAdminRoute
    }
    '/_app/pdv/': {
      id: '/_app/pdv/'
      path: '/'
      fullPath: '/pdv/'
      preLoaderRoute: typeof AppPdvIndexRouteImport
      parentRoute: typeof AppPdvRoute
    }
    '/_app/financeiro/': {
      id: '/_app/financeiro/'
      path: '/financeiro'
      fullPath: '/financeiro/'
      preLoaderRoute: typeof AppFinanceiroIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/estoque/': {
      id: '/_app/estoque/'
      path: '/estoque'
      fullPath: '/estoque/'
      preLoaderRoute: typeof AppEstoqueIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bpo/': {
      id: '/_app/bpo/'
      path: '/'
      fullPath: '/bpo/'
      preLoaderRoute: typeof AppBpoIndexRouteImport
      parentRoute: typeof AppBpoRoute
    }
    '/_app/super-admin/uso': {
      id: '/_app/super-admin/uso'
      path: '/uso'
      fullPath: '/super-admin/uso'
      preLoaderRoute: typeof AppSuperAdminUsoRouteImport
      parentRoute: typeof AppSuperAdminRoute
    }
    '/_app/super-admin/planos': {
      id: '/_app/super-admin/planos'
      path: '/planos'
      fullPath: '/super-admin/planos'
      preLoaderRoute: typeof AppSuperAdminPlanosRouteImport
      parentRoute: typeof AppSuperAdminRoute
    }
    '/_app/super-admin/nova-empresa': {
      id: '/_app/super-admin/nova-empresa'
      path: '/nova-empresa'
      fullPath: '/super-admin/nova-empresa'
      preLoaderRoute: typeof AppSuperAdminNovaEmpresaRouteImport
      parentRoute: typeof AppSuperAdminRoute
    }
    '/_app/super-admin/empresas': {
      id: '/_app/super-admin/empresas'
      path: '/empresas'
      fullPath: '/super-admin/empresas'
      preLoaderRoute: typeof AppSuperAdminEmpresasRouteImport
      parentRoute: typeof AppSuperAdminRoute
    }
    '/_app/super-admin/assinaturas': {
      id: '/_app/super-admin/assinaturas'
      path: '/assinaturas'
      fullPath: '/super-admin/assinaturas'
      preLoaderRoute: typeof AppSuperAdminAssinaturasRouteImport
      parentRoute: typeof AppSuperAdminRoute
    }
    '/_app/pdv/visao-geral': {
      id: '/_app/pdv/visao-geral'
      path: '/visao-geral'
      fullPath: '/pdv/visao-geral'
      preLoaderRoute: typeof AppPdvVisaoGeralRouteImport
      parentRoute: typeof AppPdvRoute
    }
    '/_app/pdv/trocas-devolucoes': {
      id: '/_app/pdv/trocas-devolucoes'
      path: '/trocas-devolucoes'
      fullPath: '/pdv/trocas-devolucoes'
      preLoaderRoute: typeof AppPdvTrocasDevolucoesRouteImport
      parentRoute: typeof AppPdvRoute
    }
    '/_app/pdv/historico': {
      id: '/_app/pdv/historico'
      path: '/historico'
      fullPath: '/pdv/historico'
      preLoaderRoute: typeof AppPdvHistoricoRouteImport
      parentRoute: typeof AppPdvRoute
    }
    '/_app/pdv/fiscal': {
      id: '/_app/pdv/fiscal'
      path: '/fiscal'
      fullPath: '/pdv/fiscal'
      preLoaderRoute: typeof AppPdvFiscalRouteImport
      parentRoute: typeof AppPdvRoute
    }
    '/_app/pdv/configuracoes': {
      id: '/_app/pdv/configuracoes'
      path: '/configuracoes'
      fullPath: '/pdv/configuracoes'
      preLoaderRoute: typeof AppPdvConfiguracoesRouteImport
      parentRoute: typeof AppPdvRoute
    }
    '/_app/pdv/caixa': {
      id: '/_app/pdv/caixa'
      path: '/caixa'
      fullPath: '/pdv/caixa'
      preLoaderRoute: typeof AppPdvCaixaRouteImport
      parentRoute: typeof AppPdvRoute
    }
    '/_app/financeiro/tarefas': {
      id: '/_app/financeiro/tarefas'
      path: '/financeiro/tarefas'
      fullPath: '/financeiro/tarefas'
      preLoaderRoute: typeof AppFinanceiroTarefasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/financeiro/notificacoes': {
      id: '/_app/financeiro/notificacoes'
      path: '/financeiro/notificacoes'
      fullPath: '/financeiro/notificacoes'
      preLoaderRoute: typeof AppFinanceiroNotificacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/financeiro/fluxo-caixa': {
      id: '/_app/financeiro/fluxo-caixa'
      path: '/financeiro/fluxo-caixa'
      fullPath: '/financeiro/fluxo-caixa'
      preLoaderRoute: typeof AppFinanceiroFluxoCaixaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/financeiro/dre': {
      id: '/_app/financeiro/dre'
      path: '/financeiro/dre'
      fullPath: '/financeiro/dre'
      preLoaderRoute: typeof AppFinanceiroDreRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/financeiro/contas-carteiras': {
      id: '/_app/financeiro/contas-carteiras'
      path: '/financeiro/contas-carteiras'
      fullPath: '/financeiro/contas-carteiras'
      preLoaderRoute: typeof AppFinanceiroContasCarteirasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/financeiro/contas-a-receber': {
      id: '/_app/financeiro/contas-a-receber'
      path: '/financeiro/contas-a-receber'
      fullPath: '/financeiro/contas-a-receber'
      preLoaderRoute: typeof AppFinanceiroContasAReceberRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/financeiro/contas-a-pagar': {
      id: '/_app/financeiro/contas-a-pagar'
      path: '/financeiro/contas-a-pagar'
      fullPath: '/financeiro/contas-a-pagar'
      preLoaderRoute: typeof AppFinanceiroContasAPagarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/financeiro/conciliacao': {
      id: '/_app/financeiro/conciliacao'
      path: '/financeiro/conciliacao'
      fullPath: '/financeiro/conciliacao'
      preLoaderRoute: typeof AppFinanceiroConciliacaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/financeiro/cobrancas': {
      id: '/_app/financeiro/cobrancas'
      path: '/financeiro/cobrancas'
      fullPath: '/financeiro/cobrancas'
      preLoaderRoute: typeof AppFinanceiroCobrancasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/financeiro/cartoes': {
      id: '/_app/financeiro/cartoes'
      path: '/financeiro/cartoes'
      fullPath: '/financeiro/cartoes'
      preLoaderRoute: typeof AppFinanceiroCartoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/estoque/transferencias': {
      id: '/_app/estoque/transferencias'
      path: '/estoque/transferencias'
      fullPath: '/estoque/transferencias'
      preLoaderRoute: typeof AppEstoqueTransferenciasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/estoque/reposicao': {
      id: '/_app/estoque/reposicao'
      path: '/estoque/reposicao'
      fullPath: '/estoque/reposicao'
      preLoaderRoute: typeof AppEstoqueReposicaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/estoque/recebimento': {
      id: '/_app/estoque/recebimento'
      path: '/estoque/recebimento'
      fullPath: '/estoque/recebimento'
      preLoaderRoute: typeof AppEstoqueRecebimentoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/estoque/produtos': {
      id: '/_app/estoque/produtos'
      path: '/estoque/produtos'
      fullPath: '/estoque/produtos'
      preLoaderRoute: typeof AppEstoqueProdutosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/estoque/perdas': {
      id: '/_app/estoque/perdas'
      path: '/estoque/perdas'
      fullPath: '/estoque/perdas'
      preLoaderRoute: typeof AppEstoquePerdasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/estoque/movimentacoes': {
      id: '/_app/estoque/movimentacoes'
      path: '/estoque/movimentacoes'
      fullPath: '/estoque/movimentacoes'
      preLoaderRoute: typeof AppEstoqueMovimentacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/estoque/locais': {
      id: '/_app/estoque/locais'
      path: '/estoque/locais'
      fullPath: '/estoque/locais'
      preLoaderRoute: typeof AppEstoqueLocaisRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/estoque/inventario': {
      id: '/_app/estoque/inventario'
      path: '/estoque/inventario'
      fullPath: '/estoque/inventario'
      preLoaderRoute: typeof AppEstoqueInventarioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/estoque/consulta': {
      id: '/_app/estoque/consulta'
      path: '/estoque/consulta'
      fullPath: '/estoque/consulta'
      preLoaderRoute: typeof AppEstoqueConsultaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bpo/tarefas': {
      id: '/_app/bpo/tarefas'
      path: '/tarefas'
      fullPath: '/bpo/tarefas'
      preLoaderRoute: typeof AppBpoTarefasRouteImport
      parentRoute: typeof AppBpoRoute
    }
    '/_app/bpo/relatorios': {
      id: '/_app/bpo/relatorios'
      path: '/relatorios'
      fullPath: '/bpo/relatorios'
      preLoaderRoute: typeof AppBpoRelatoriosRouteImport
      parentRoute: typeof AppBpoRoute
    }
    '/_app/bpo/pendencias': {
      id: '/_app/bpo/pendencias'
      path: '/pendencias'
      fullPath: '/bpo/pendencias'
      preLoaderRoute: typeof AppBpoPendenciasRouteImport
      parentRoute: typeof AppBpoRoute
    }
    '/_app/bpo/lancamentos': {
      id: '/_app/bpo/lancamentos'
      path: '/lancamentos'
      fullPath: '/bpo/lancamentos'
      preLoaderRoute: typeof AppBpoLancamentosRouteImport
      parentRoute: typeof AppBpoRoute
    }
    '/_app/bpo/honorarios': {
      id: '/_app/bpo/honorarios'
      path: '/honorarios'
      fullPath: '/bpo/honorarios'
      preLoaderRoute: typeof AppBpoHonorariosRouteImport
      parentRoute: typeof AppBpoRoute
    }
    '/_app/bpo/fechamento': {
      id: '/_app/bpo/fechamento'
      path: '/fechamento'
      fullPath: '/bpo/fechamento'
      preLoaderRoute: typeof AppBpoFechamentoRouteImport
      parentRoute: typeof AppBpoRoute
    }
    '/_app/bpo/documentos': {
      id: '/_app/bpo/documentos'
      path: '/documentos'
      fullPath: '/bpo/documentos'
      preLoaderRoute: typeof AppBpoDocumentosRouteImport
      parentRoute: typeof AppBpoRoute
    }
    '/_app/bpo/configuracoes': {
      id: '/_app/bpo/configuracoes'
      path: '/configuracoes'
      fullPath: '/bpo/configuracoes'
      preLoaderRoute: typeof AppBpoConfiguracoesRouteImport
      parentRoute: typeof AppBpoRoute
    }
    '/_app/bpo/conciliacao': {
      id: '/_app/bpo/conciliacao'
      path: '/conciliacao'
      fullPath: '/bpo/conciliacao'
      preLoaderRoute: typeof AppBpoConciliacaoRouteImport
      parentRoute: typeof AppBpoRoute
    }
    '/_app/bpo/comunicacao': {
      id: '/_app/bpo/comunicacao'
      path: '/comunicacao'
      fullPath: '/bpo/comunicacao'
      preLoaderRoute: typeof AppBpoComunicacaoRouteImport
      parentRoute: typeof AppBpoRoute
    }
    '/_app/bpo/clientes': {
      id: '/_app/bpo/clientes'
      path: '/clientes'
      fullPath: '/bpo/clientes'
      preLoaderRoute: typeof AppBpoClientesRouteImport
      parentRoute: typeof AppBpoRoute
    }
    '/_app/bpo/analise': {
      id: '/_app/bpo/analise'
      path: '/analise'
      fullPath: '/bpo/analise'
      preLoaderRoute: typeof AppBpoAnaliseRouteImport
      parentRoute: typeof AppBpoRoute
    }
  }
}

interface AppBpoRouteChildren {
  AppBpoAnaliseRoute: typeof AppBpoAnaliseRoute
  AppBpoClientesRoute: typeof AppBpoClientesRoute
  AppBpoComunicacaoRoute: typeof AppBpoComunicacaoRoute
  AppBpoConciliacaoRoute: typeof AppBpoConciliacaoRoute
  AppBpoConfiguracoesRoute: typeof AppBpoConfiguracoesRoute
  AppBpoDocumentosRoute: typeof AppBpoDocumentosRoute
  AppBpoFechamentoRoute: typeof AppBpoFechamentoRoute
  AppBpoHonorariosRoute: typeof AppBpoHonorariosRoute
  AppBpoLancamentosRoute: typeof AppBpoLancamentosRoute
  AppBpoPendenciasRoute: typeof AppBpoPendenciasRoute
  AppBpoRelatoriosRoute: typeof AppBpoRelatoriosRoute
  AppBpoTarefasRoute: typeof AppBpoTarefasRoute
  AppBpoIndexRoute: typeof AppBpoIndexRoute
}

const AppBpoRouteChildren: AppBpoRouteChildren = {
  AppBpoAnaliseRoute: AppBpoAnaliseRoute,
  AppBpoClientesRoute: AppBpoClientesRoute,
  AppBpoComunicacaoRoute: AppBpoComunicacaoRoute,
  AppBpoConciliacaoRoute: AppBpoConciliacaoRoute,
  AppBpoConfiguracoesRoute: AppBpoConfiguracoesRoute,
  AppBpoDocumentosRoute: AppBpoDocumentosRoute,
  AppBpoFechamentoRoute: AppBpoFechamentoRoute,
  AppBpoHonorariosRoute: AppBpoHonorariosRoute,
  AppBpoLancamentosRoute: AppBpoLancamentosRoute,
  AppBpoPendenciasRoute: AppBpoPendenciasRoute,
  AppBpoRelatoriosRoute: AppBpoRelatoriosRoute,
  AppBpoTarefasRoute: AppBpoTarefasRoute,
  AppBpoIndexRoute: AppBpoIndexRoute,
}

const AppBpoRouteWithChildren =
  AppBpoRoute._addFileChildren(AppBpoRouteChildren)

interface AppPdvRouteChildren {
  AppPdvCaixaRoute: typeof AppPdvCaixaRoute
  AppPdvConfiguracoesRoute: typeof AppPdvConfiguracoesRoute
  AppPdvFiscalRoute: typeof AppPdvFiscalRoute
  AppPdvHistoricoRoute: typeof AppPdvHistoricoRoute
  AppPdvTrocasDevolucoesRoute: typeof AppPdvTrocasDevolucoesRoute
  AppPdvVisaoGeralRoute: typeof AppPdvVisaoGeralRoute
  AppPdvIndexRoute: typeof AppPdvIndexRoute
}

const AppPdvRouteChildren: AppPdvRouteChildren = {
  AppPdvCaixaRoute: AppPdvCaixaRoute,
  AppPdvConfiguracoesRoute: AppPdvConfiguracoesRoute,
  AppPdvFiscalRoute: AppPdvFiscalRoute,
  AppPdvHistoricoRoute: AppPdvHistoricoRoute,
  AppPdvTrocasDevolucoesRoute: AppPdvTrocasDevolucoesRoute,
  AppPdvVisaoGeralRoute: AppPdvVisaoGeralRoute,
  AppPdvIndexRoute: AppPdvIndexRoute,
}

const AppPdvRouteWithChildren =
  AppPdvRoute._addFileChildren(AppPdvRouteChildren)

interface AppSuperAdminRouteChildren {
  AppSuperAdminAssinaturasRoute: typeof AppSuperAdminAssinaturasRoute
  AppSuperAdminEmpresasRoute: typeof AppSuperAdminEmpresasRoute
  AppSuperAdminNovaEmpresaRoute: typeof AppSuperAdminNovaEmpresaRoute
  AppSuperAdminPlanosRoute: typeof AppSuperAdminPlanosRoute
  AppSuperAdminUsoRoute: typeof AppSuperAdminUsoRoute
  AppSuperAdminIndexRoute: typeof AppSuperAdminIndexRoute
}

const AppSuperAdminRouteChildren: AppSuperAdminRouteChildren = {
  AppSuperAdminAssinaturasRoute: AppSuperAdminAssinaturasRoute,
  AppSuperAdminEmpresasRoute: AppSuperAdminEmpresasRoute,
  AppSuperAdminNovaEmpresaRoute: AppSuperAdminNovaEmpresaRoute,
  AppSuperAdminPlanosRoute: AppSuperAdminPlanosRoute,
  AppSuperAdminUsoRoute: AppSuperAdminUsoRoute,
  AppSuperAdminIndexRoute: AppSuperAdminIndexRoute,
}

const AppSuperAdminRouteWithChildren = AppSuperAdminRoute._addFileChildren(
  AppSuperAdminRouteChildren,
)

interface AppRouteChildren {
  AppAgendaRoute: typeof AppAgendaRoute
  AppBpoRoute: typeof AppBpoRouteWithChildren
  AppCadastrosRoute: typeof AppCadastrosRoute
  AppChatRoute: typeof AppChatRoute
  AppComprasRoute: typeof AppComprasRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppControleRoute: typeof AppControleRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFiscalRoute: typeof AppFiscalRoute
  AppImportacaoRoute: typeof AppImportacaoRoute
  AppNotificacoesRoute: typeof AppNotificacoesRoute
  AppPdvRoute: typeof AppPdvRouteWithChildren
  AppPerfilRoute: typeof AppPerfilRoute
  AppPosVendaRoute: typeof AppPosVendaRoute
  AppRelatoriosRoute: typeof AppRelatoriosRoute
  AppSuperAdminRoute: typeof AppSuperAdminRouteWithChildren
  AppTarefasRoute: typeof AppTarefasRoute
  AppVendasRoute: typeof AppVendasRoute
  AppEstoqueConsultaRoute: typeof AppEstoqueConsultaRoute
  AppEstoqueInventarioRoute: typeof AppEstoqueInventarioRoute
  AppEstoqueLocaisRoute: typeof AppEstoqueLocaisRoute
  AppEstoqueMovimentacoesRoute: typeof AppEstoqueMovimentacoesRoute
  AppEstoquePerdasRoute: typeof AppEstoquePerdasRoute
  AppEstoqueProdutosRoute: typeof AppEstoqueProdutosRoute
  AppEstoqueRecebimentoRoute: typeof AppEstoqueRecebimentoRoute
  AppEstoqueReposicaoRoute: typeof AppEstoqueReposicaoRoute
  AppEstoqueTransferenciasRoute: typeof AppEstoqueTransferenciasRoute
  AppFinanceiroCartoesRoute: typeof AppFinanceiroCartoesRoute
  AppFinanceiroCobrancasRoute: typeof AppFinanceiroCobrancasRoute
  AppFinanceiroConciliacaoRoute: typeof AppFinanceiroConciliacaoRoute
  AppFinanceiroContasAPagarRoute: typeof AppFinanceiroContasAPagarRoute
  AppFinanceiroContasAReceberRoute: typeof AppFinanceiroContasAReceberRoute
  AppFinanceiroContasCarteirasRoute: typeof AppFinanceiroContasCarteirasRoute
  AppFinanceiroDreRoute: typeof AppFinanceiroDreRoute
  AppFinanceiroFluxoCaixaRoute: typeof AppFinanceiroFluxoCaixaRoute
  AppFinanceiroNotificacoesRoute: typeof AppFinanceiroNotificacoesRoute
  AppFinanceiroTarefasRoute: typeof AppFinanceiroTarefasRoute
  AppEstoqueIndexRoute: typeof AppEstoqueIndexRoute
  AppFinanceiroIndexRoute: typeof AppFinanceiroIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgendaRoute: AppAgendaRoute,
  AppBpoRoute: AppBpoRouteWithChildren,
  AppCadastrosRoute: AppCadastrosRoute,
  AppChatRoute: AppChatRoute,
  AppComprasRoute: AppComprasRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppControleRoute: AppControleRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFiscalRoute: AppFiscalRoute,
  AppImportacaoRoute: AppImportacaoRoute,
  AppNotificacoesRoute: AppNotificacoesRoute,
  AppPdvRoute: AppPdvRouteWithChildren,
  AppPerfilRoute: AppPerfilRoute,
  AppPosVendaRoute: AppPosVendaRoute,
  AppRelatoriosRoute: AppRelatoriosRoute,
  AppSuperAdminRoute: AppSuperAdminRouteWithChildren,
  AppTarefasRoute: AppTarefasRoute,
  AppVendasRoute: AppVendasRoute,
  AppEstoqueConsultaRoute: AppEstoqueConsultaRoute,
  AppEstoqueInventarioRoute: AppEstoqueInventarioRoute,
  AppEstoqueLocaisRoute: AppEstoqueLocaisRoute,
  AppEstoqueMovimentacoesRoute: AppEstoqueMovimentacoesRoute,
  AppEstoquePerdasRoute: AppEstoquePerdasRoute,
  AppEstoqueProdutosRoute: AppEstoqueProdutosRoute,
  AppEstoqueRecebimentoRoute: AppEstoqueRecebimentoRoute,
  AppEstoqueReposicaoRoute: AppEstoqueReposicaoRoute,
  AppEstoqueTransferenciasRoute: AppEstoqueTransferenciasRoute,
  AppFinanceiroCartoesRoute: AppFinanceiroCartoesRoute,
  AppFinanceiroCobrancasRoute: AppFinanceiroCobrancasRoute,
  AppFinanceiroConciliacaoRoute: AppFinanceiroConciliacaoRoute,
  AppFinanceiroContasAPagarRoute: AppFinanceiroContasAPagarRoute,
  AppFinanceiroContasAReceberRoute: AppFinanceiroContasAReceberRoute,
  AppFinanceiroContasCarteirasRoute: AppFinanceiroContasCarteirasRoute,
  AppFinanceiroDreRoute: AppFinanceiroDreRoute,
  AppFinanceiroFluxoCaixaRoute: AppFinanceiroFluxoCaixaRoute,
  AppFinanceiroNotificacoesRoute: AppFinanceiroNotificacoesRoute,
  AppFinanceiroTarefasRoute: AppFinanceiroTarefasRoute,
  AppEstoqueIndexRoute: AppEstoqueIndexRoute,
  AppFinanceiroIndexRoute: AppFinanceiroIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
